//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace V2012
{

    // 
    // This source code was auto-generated by xsd, Version=4.0.30319.17929.
    // 


    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true,
        Namespace = "http://microsoft.com/schemas/VisualStudio/TeamTest/2010")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "http://microsoft.com/schemas/VisualStudio/TeamTest/2010",
        IsNullable = false)]
    public partial class TestRun
    {

        private TestRunTestSettings testSettingsField;

        private TestRunTimes timesField;

        private TestRunResultSummary resultSummaryField;

        private TestRunUnitTest[] testDefinitionsField;

        private TestRunTestList[] testListsField;

        private TestRunTestEntry[] testEntriesField;

        private TestRunResults resultsField;

        private string idField;

        private string nameField;

        private string runUserField;

        /// <remarks/>
        public TestRunTestSettings TestSettings
        {
            get { return this.testSettingsField; }
            set { this.testSettingsField = value; }
        }

        /// <remarks/>
        public TestRunTimes Times
        {
            get { return this.timesField; }
            set { this.timesField = value; }
        }

        /// <remarks/>
        public TestRunResultSummary ResultSummary
        {
            get { return this.resultSummaryField; }
            set { this.resultSummaryField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("UnitTest", IsNullable = false)]
        public TestRunUnitTest[] TestDefinitions
        {
            get { return this.testDefinitionsField; }
            set { this.testDefinitionsField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("TestList", IsNullable = false)]
        public TestRunTestList[] TestLists
        {
            get { return this.testListsField; }
            set { this.testListsField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("TestEntry", IsNullable = false)]
        public TestRunTestEntry[] TestEntries
        {
            get { return this.testEntriesField; }
            set { this.testEntriesField = value; }
        }

        /// <remarks/>
        public TestRunResults Results
        {
            get { return this.resultsField; }
            set { this.resultsField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string id
        {
            get { return this.idField; }
            set { this.idField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string name
        {
            get { return this.nameField; }
            set { this.nameField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string runUser
        {
            get { return this.runUserField; }
            set { this.runUserField = value; }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true,
        Namespace = "http://microsoft.com/schemas/VisualStudio/TeamTest/2010")]
    public partial class TestRunTestSettings
    {

        private TestRunTestSettingsDeployment deploymentField;

        private TestRunTestSettingsExecution executionField;

        private string nameField;

        private string idField;

        /// <remarks/>
        public TestRunTestSettingsDeployment Deployment
        {
            get { return this.deploymentField; }
            set { this.deploymentField = value; }
        }

        /// <remarks/>
        public TestRunTestSettingsExecution Execution
        {
            get { return this.executionField; }
            set { this.executionField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string name
        {
            get { return this.nameField; }
            set { this.nameField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string id
        {
            get { return this.idField; }
            set { this.idField = value; }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true,
        Namespace = "http://microsoft.com/schemas/VisualStudio/TeamTest/2010")]
    public partial class TestRunTestSettingsDeployment
    {

        private string userDeploymentRootField;

        private string useDefaultDeploymentRootField;

        private string runDeploymentRootField;

        private string valueField;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string userDeploymentRoot
        {
            get { return this.userDeploymentRootField; }
            set { this.userDeploymentRootField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string useDefaultDeploymentRoot
        {
            get { return this.useDefaultDeploymentRootField; }
            set { this.useDefaultDeploymentRootField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string runDeploymentRoot
        {
            get { return this.runDeploymentRootField; }
            set { this.runDeploymentRootField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value
        {
            get { return this.valueField; }
            set { this.valueField = value; }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true,
        Namespace = "http://microsoft.com/schemas/VisualStudio/TeamTest/2010")]
    public partial class TestRunTestSettingsExecution
    {

        private string testTypeSpecificField;

        private TestRunTestSettingsExecutionAgentRule agentRuleField;

        /// <remarks/>
        public string TestTypeSpecific
        {
            get { return this.testTypeSpecificField; }
            set { this.testTypeSpecificField = value; }
        }

        /// <remarks/>
        public TestRunTestSettingsExecutionAgentRule AgentRule
        {
            get { return this.agentRuleField; }
            set { this.agentRuleField = value; }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true,
        Namespace = "http://microsoft.com/schemas/VisualStudio/TeamTest/2010")]
    public partial class TestRunTestSettingsExecutionAgentRule
    {

        private string nameField;

        private string valueField;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string name
        {
            get { return this.nameField; }
            set { this.nameField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value
        {
            get { return this.valueField; }
            set { this.valueField = value; }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true,
        Namespace = "http://microsoft.com/schemas/VisualStudio/TeamTest/2010")]
    public partial class TestRunTimes
    {

        private System.DateTime creationField;

        private bool creationFieldSpecified;

        private System.DateTime queuingField;

        private bool queuingFieldSpecified;

        private System.DateTime startField;

        private bool startFieldSpecified;

        private System.DateTime finishField;

        private bool finishFieldSpecified;

        private string valueField;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public System.DateTime creation
        {
            get { return this.creationField; }
            set { this.creationField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool creationSpecified
        {
            get { return this.creationFieldSpecified; }
            set { this.creationFieldSpecified = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public System.DateTime queuing
        {
            get { return this.queuingField; }
            set { this.queuingField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool queuingSpecified
        {
            get { return this.queuingFieldSpecified; }
            set { this.queuingFieldSpecified = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public System.DateTime start
        {
            get { return this.startField; }
            set { this.startField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool startSpecified
        {
            get { return this.startFieldSpecified; }
            set { this.startFieldSpecified = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public System.DateTime finish
        {
            get { return this.finishField; }
            set { this.finishField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool finishSpecified
        {
            get { return this.finishFieldSpecified; }
            set { this.finishFieldSpecified = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value
        {
            get { return this.valueField; }
            set { this.valueField = value; }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true,
        Namespace = "http://microsoft.com/schemas/VisualStudio/TeamTest/2010")]
    public partial class TestRunResultSummary
    {

        private TestRunResultSummaryCounters countersField;

        private TestRunResultSummaryRunInfos runInfosField;

        private string outcomeField;

        /// <remarks/>
        public TestRunResultSummaryCounters Counters
        {
            get { return this.countersField; }
            set { this.countersField = value; }
        }

        /// <remarks/>
        public TestRunResultSummaryRunInfos RunInfos
        {
            get { return this.runInfosField; }
            set { this.runInfosField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string outcome
        {
            get { return this.outcomeField; }
            set { this.outcomeField = value; }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true,
        Namespace = "http://microsoft.com/schemas/VisualStudio/TeamTest/2010")]
    public partial class TestRunResultSummaryCounters
    {

        private sbyte totalField;

        private bool totalFieldSpecified;

        private sbyte executedField;

        private bool executedFieldSpecified;

        private sbyte errorField;

        private bool errorFieldSpecified;

        private sbyte failedField;

        private bool failedFieldSpecified;

        private sbyte timeoutField;

        private bool timeoutFieldSpecified;

        private sbyte abortedField;

        private bool abortedFieldSpecified;

        private sbyte inconclusiveField;

        private bool inconclusiveFieldSpecified;

        private sbyte passedButRunAbortedField;

        private bool passedButRunAbortedFieldSpecified;

        private sbyte notRunnableField;

        private bool notRunnableFieldSpecified;

        private sbyte notExecutedField;

        private bool notExecutedFieldSpecified;

        private sbyte disconnectedField;

        private bool disconnectedFieldSpecified;

        private sbyte warningField;

        private bool warningFieldSpecified;

        private sbyte passedField;

        private bool passedFieldSpecified;

        private sbyte completedField;

        private bool completedFieldSpecified;

        private sbyte inProgressField;

        private bool inProgressFieldSpecified;

        private sbyte pendingField;

        private bool pendingFieldSpecified;

        private string valueField;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public sbyte total
        {
            get { return this.totalField; }
            set { this.totalField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool totalSpecified
        {
            get { return this.totalFieldSpecified; }
            set { this.totalFieldSpecified = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public sbyte executed
        {
            get { return this.executedField; }
            set { this.executedField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool executedSpecified
        {
            get { return this.executedFieldSpecified; }
            set { this.executedFieldSpecified = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public sbyte error
        {
            get { return this.errorField; }
            set { this.errorField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool errorSpecified
        {
            get { return this.errorFieldSpecified; }
            set { this.errorFieldSpecified = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public sbyte failed
        {
            get { return this.failedField; }
            set { this.failedField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool failedSpecified
        {
            get { return this.failedFieldSpecified; }
            set { this.failedFieldSpecified = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public sbyte timeout
        {
            get { return this.timeoutField; }
            set { this.timeoutField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool timeoutSpecified
        {
            get { return this.timeoutFieldSpecified; }
            set { this.timeoutFieldSpecified = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public sbyte aborted
        {
            get { return this.abortedField; }
            set { this.abortedField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool abortedSpecified
        {
            get { return this.abortedFieldSpecified; }
            set { this.abortedFieldSpecified = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public sbyte inconclusive
        {
            get { return this.inconclusiveField; }
            set { this.inconclusiveField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool inconclusiveSpecified
        {
            get { return this.inconclusiveFieldSpecified; }
            set { this.inconclusiveFieldSpecified = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public sbyte passedButRunAborted
        {
            get { return this.passedButRunAbortedField; }
            set { this.passedButRunAbortedField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool passedButRunAbortedSpecified
        {
            get { return this.passedButRunAbortedFieldSpecified; }
            set { this.passedButRunAbortedFieldSpecified = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public sbyte notRunnable
        {
            get { return this.notRunnableField; }
            set { this.notRunnableField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool notRunnableSpecified
        {
            get { return this.notRunnableFieldSpecified; }
            set { this.notRunnableFieldSpecified = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public sbyte notExecuted
        {
            get { return this.notExecutedField; }
            set { this.notExecutedField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool notExecutedSpecified
        {
            get { return this.notExecutedFieldSpecified; }
            set { this.notExecutedFieldSpecified = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public sbyte disconnected
        {
            get { return this.disconnectedField; }
            set { this.disconnectedField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool disconnectedSpecified
        {
            get { return this.disconnectedFieldSpecified; }
            set { this.disconnectedFieldSpecified = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public sbyte warning
        {
            get { return this.warningField; }
            set { this.warningField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool warningSpecified
        {
            get { return this.warningFieldSpecified; }
            set { this.warningFieldSpecified = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public sbyte passed
        {
            get { return this.passedField; }
            set { this.passedField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool passedSpecified
        {
            get { return this.passedFieldSpecified; }
            set { this.passedFieldSpecified = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public sbyte completed
        {
            get { return this.completedField; }
            set { this.completedField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool completedSpecified
        {
            get { return this.completedFieldSpecified; }
            set { this.completedFieldSpecified = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public sbyte inProgress
        {
            get { return this.inProgressField; }
            set { this.inProgressField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool inProgressSpecified
        {
            get { return this.inProgressFieldSpecified; }
            set { this.inProgressFieldSpecified = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public sbyte pending
        {
            get { return this.pendingField; }
            set { this.pendingField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool pendingSpecified
        {
            get { return this.pendingFieldSpecified; }
            set { this.pendingFieldSpecified = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value
        {
            get { return this.valueField; }
            set { this.valueField = value; }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true,
        Namespace = "http://microsoft.com/schemas/VisualStudio/TeamTest/2010")]
    public partial class TestRunResultSummaryRunInfos
    {

        private TestRunResultSummaryRunInfosRunInfo runInfoField;

        /// <remarks/>
        public TestRunResultSummaryRunInfosRunInfo RunInfo
        {
            get { return this.runInfoField; }
            set { this.runInfoField = value; }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true,
        Namespace = "http://microsoft.com/schemas/VisualStudio/TeamTest/2010")]
    public partial class TestRunResultSummaryRunInfosRunInfo
    {

        private string textField;

        private string computerNameField;

        private string outcomeField;

        private System.DateTime timestampField;

        private bool timestampFieldSpecified;

        /// <remarks/>
        public string Text
        {
            get { return this.textField; }
            set { this.textField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string computerName
        {
            get { return this.computerNameField; }
            set { this.computerNameField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string outcome
        {
            get { return this.outcomeField; }
            set { this.outcomeField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public System.DateTime timestamp
        {
            get { return this.timestampField; }
            set { this.timestampField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool timestampSpecified
        {
            get { return this.timestampFieldSpecified; }
            set { this.timestampFieldSpecified = value; }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true,
        Namespace = "http://microsoft.com/schemas/VisualStudio/TeamTest/2010")]
    public partial class TestRunUnitTest
    {

        private TestRunUnitTestTestCategory testCategoryField;

        private TestRunUnitTestExecution executionField;

        private TestRunUnitTestTestMethod testMethodField;

        private string extensionField;

        private string nameField;

        private string storageField;

        private string idField;

        /// <remarks/>
        public TestRunUnitTestTestCategory TestCategory
        {
            get { return this.testCategoryField; }
            set { this.testCategoryField = value; }
        }

        /// <remarks/>
        public TestRunUnitTestExecution Execution
        {
            get { return this.executionField; }
            set { this.executionField = value; }
        }

        /// <remarks/>
        public TestRunUnitTestTestMethod TestMethod
        {
            get { return this.testMethodField; }
            set { this.testMethodField = value; }
        }

        /// <remarks/>
        public string Extension
        {
            get { return this.extensionField; }
            set { this.extensionField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string name
        {
            get { return this.nameField; }
            set { this.nameField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string storage
        {
            get { return this.storageField; }
            set { this.storageField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string id
        {
            get { return this.idField; }
            set { this.idField = value; }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true,
        Namespace = "http://microsoft.com/schemas/VisualStudio/TeamTest/2010")]
    public partial class TestRunUnitTestTestCategory
    {

        private TestRunUnitTestTestCategoryTestCategoryItem testCategoryItemField;

        /// <remarks/>
        public TestRunUnitTestTestCategoryTestCategoryItem TestCategoryItem
        {
            get { return this.testCategoryItemField; }
            set { this.testCategoryItemField = value; }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true,
        Namespace = "http://microsoft.com/schemas/VisualStudio/TeamTest/2010")]
    public partial class TestRunUnitTestTestCategoryTestCategoryItem
    {

        private string testCategoryField;

        private string valueField;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string TestCategory
        {
            get { return this.testCategoryField; }
            set { this.testCategoryField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value
        {
            get { return this.valueField; }
            set { this.valueField = value; }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true,
        Namespace = "http://microsoft.com/schemas/VisualStudio/TeamTest/2010")]
    public partial class TestRunUnitTestExecution
    {

        private string idField;

        private string valueField;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string id
        {
            get { return this.idField; }
            set { this.idField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value
        {
            get { return this.valueField; }
            set { this.valueField = value; }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true,
        Namespace = "http://microsoft.com/schemas/VisualStudio/TeamTest/2010")]
    public partial class TestRunUnitTestTestMethod
    {

        private string codeBaseField;

        private string adapterTypeNameField;

        private string classNameField;

        private string nameField;

        private string valueField;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string codeBase
        {
            get { return this.codeBaseField; }
            set { this.codeBaseField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string adapterTypeName
        {
            get { return this.adapterTypeNameField; }
            set { this.adapterTypeNameField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string className
        {
            get { return this.classNameField; }
            set { this.classNameField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string name
        {
            get { return this.nameField; }
            set { this.nameField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value
        {
            get { return this.valueField; }
            set { this.valueField = value; }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true,
        Namespace = "http://microsoft.com/schemas/VisualStudio/TeamTest/2010")]
    public partial class TestRunTestList
    {

        private string nameField;

        private string idField;

        private string valueField;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string name
        {
            get { return this.nameField; }
            set { this.nameField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string id
        {
            get { return this.idField; }
            set { this.idField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value
        {
            get { return this.valueField; }
            set { this.valueField = value; }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true,
        Namespace = "http://microsoft.com/schemas/VisualStudio/TeamTest/2010")]
    public partial class TestRunTestEntry
    {

        private string testIdField;

        private string executionIdField;

        private string testListIdField;

        private string valueField;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string testId
        {
            get { return this.testIdField; }
            set { this.testIdField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string executionId
        {
            get { return this.executionIdField; }
            set { this.executionIdField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string testListId
        {
            get { return this.testListIdField; }
            set { this.testListIdField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value
        {
            get { return this.valueField; }
            set { this.valueField = value; }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true,
        Namespace = "http://microsoft.com/schemas/VisualStudio/TeamTest/2010")]
    public partial class TestRunResults
    {

        private TestRunResultsUnitTestResult[] unitTestResultField;

        private TestRunResultsTestResultAggregation testResultAggregationField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("UnitTestResult")]
        public TestRunResultsUnitTestResult[] UnitTestResult
        {
            get { return this.unitTestResultField; }
            set { this.unitTestResultField = value; }
        }

        /// <remarks/>
        public TestRunResultsTestResultAggregation TestResultAggregation
        {
            get { return this.testResultAggregationField; }
            set { this.testResultAggregationField = value; }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true,
        Namespace = "http://microsoft.com/schemas/VisualStudio/TeamTest/2010")]
    public partial class TestRunResultsUnitTestResult
    {

        private TestRunResultsUnitTestResultOutput outputField;

        private TestRunResultsUnitTestResultResultFiles resultFilesField;

        private string extensionResultField;

        private TestRunResultsUnitTestResultCounters countersField;

        private TestRunResultsUnitTestResultInnerResults innerResultsField;

        private string executionIdField;

        private string testIdField;

        private string testNameField;

        private string computerNameField;

        private System.DateTime durationField;

        private bool durationFieldSpecified;

        private System.DateTime startTimeField;

        private bool startTimeFieldSpecified;

        private System.DateTime endTimeField;

        private bool endTimeFieldSpecified;

        private string testTypeField;

        private string outcomeField;

        private string testListIdField;

        private string relativeResultsDirectoryField;

        private string resultTypeField;

        /// <remarks/>
        public TestRunResultsUnitTestResultOutput Output
        {
            get { return this.outputField; }
            set { this.outputField = value; }
        }

        /// <remarks/>
        public TestRunResultsUnitTestResultResultFiles ResultFiles
        {
            get { return this.resultFilesField; }
            set { this.resultFilesField = value; }
        }

        /// <remarks/>
        public string ExtensionResult
        {
            get { return this.extensionResultField; }
            set { this.extensionResultField = value; }
        }

        /// <remarks/>
        public TestRunResultsUnitTestResultCounters Counters
        {
            get { return this.countersField; }
            set { this.countersField = value; }
        }

        /// <remarks/>
        public TestRunResultsUnitTestResultInnerResults InnerResults
        {
            get { return this.innerResultsField; }
            set { this.innerResultsField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string executionId
        {
            get { return this.executionIdField; }
            set { this.executionIdField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string testId
        {
            get { return this.testIdField; }
            set { this.testIdField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string testName
        {
            get { return this.testNameField; }
            set { this.testNameField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string computerName
        {
            get { return this.computerNameField; }
            set { this.computerNameField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType = "time")]
        public System.DateTime duration
        {
            get { return this.durationField; }
            set { this.durationField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool durationSpecified
        {
            get { return this.durationFieldSpecified; }
            set { this.durationFieldSpecified = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public System.DateTime startTime
        {
            get { return this.startTimeField; }
            set { this.startTimeField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool startTimeSpecified
        {
            get { return this.startTimeFieldSpecified; }
            set { this.startTimeFieldSpecified = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public System.DateTime endTime
        {
            get { return this.endTimeField; }
            set { this.endTimeField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool endTimeSpecified
        {
            get { return this.endTimeFieldSpecified; }
            set { this.endTimeFieldSpecified = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string testType
        {
            get { return this.testTypeField; }
            set { this.testTypeField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string outcome
        {
            get { return this.outcomeField; }
            set { this.outcomeField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string testListId
        {
            get { return this.testListIdField; }
            set { this.testListIdField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string relativeResultsDirectory
        {
            get { return this.relativeResultsDirectoryField; }
            set { this.relativeResultsDirectoryField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string resultType
        {
            get { return this.resultTypeField; }
            set { this.resultTypeField = value; }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true,
        Namespace = "http://microsoft.com/schemas/VisualStudio/TeamTest/2010")]
    public partial class TestRunResultsUnitTestResultOutput
    {

        private TestRunResultsUnitTestResultOutputErrorInfo errorInfoField;

        private string[] textMessagesField;

        /// <remarks/>
        public TestRunResultsUnitTestResultOutputErrorInfo ErrorInfo
        {
            get { return this.errorInfoField; }
            set { this.errorInfoField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("Message", IsNullable = false)]
        public string[] TextMessages
        {
            get { return this.textMessagesField; }
            set { this.textMessagesField = value; }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true,
        Namespace = "http://microsoft.com/schemas/VisualStudio/TeamTest/2010")]
    public partial class TestRunResultsUnitTestResultOutputErrorInfo
    {

        private string messageField;

        private string stackTraceField;

        /// <remarks/>
        public string Message
        {
            get { return this.messageField; }
            set { this.messageField = value; }
        }

        /// <remarks/>
        public string StackTrace
        {
            get { return this.stackTraceField; }
            set { this.stackTraceField = value; }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true,
        Namespace = "http://microsoft.com/schemas/VisualStudio/TeamTest/2010")]
    public partial class TestRunResultsUnitTestResultResultFiles
    {

        private TestRunResultsUnitTestResultResultFilesResultFile resultFileField;

        /// <remarks/>
        public TestRunResultsUnitTestResultResultFilesResultFile ResultFile
        {
            get { return this.resultFileField; }
            set { this.resultFileField = value; }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true,
        Namespace = "http://microsoft.com/schemas/VisualStudio/TeamTest/2010")]
    public partial class TestRunResultsUnitTestResultResultFilesResultFile
    {

        private string pathField;

        private string valueField;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string path
        {
            get { return this.pathField; }
            set { this.pathField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value
        {
            get { return this.valueField; }
            set { this.valueField = value; }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true,
        Namespace = "http://microsoft.com/schemas/VisualStudio/TeamTest/2010")]
    public partial class TestRunResultsUnitTestResultCounters
    {

        private sbyte errorField;

        private bool errorFieldSpecified;

        private sbyte failedField;

        private bool failedFieldSpecified;

        private sbyte timeoutField;

        private bool timeoutFieldSpecified;

        private sbyte abortedField;

        private bool abortedFieldSpecified;

        private sbyte inconclusiveField;

        private bool inconclusiveFieldSpecified;

        private sbyte passedButRunAbortedField;

        private bool passedButRunAbortedFieldSpecified;

        private sbyte notRunnableField;

        private bool notRunnableFieldSpecified;

        private sbyte notExecutedField;

        private bool notExecutedFieldSpecified;

        private sbyte disconnectedField;

        private bool disconnectedFieldSpecified;

        private sbyte warningField;

        private bool warningFieldSpecified;

        private sbyte passedField;

        private bool passedFieldSpecified;

        private sbyte completedField;

        private bool completedFieldSpecified;

        private sbyte inProgressField;

        private bool inProgressFieldSpecified;

        private sbyte pendingField;

        private bool pendingFieldSpecified;

        private string valueField;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public sbyte error
        {
            get { return this.errorField; }
            set { this.errorField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool errorSpecified
        {
            get { return this.errorFieldSpecified; }
            set { this.errorFieldSpecified = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public sbyte failed
        {
            get { return this.failedField; }
            set { this.failedField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool failedSpecified
        {
            get { return this.failedFieldSpecified; }
            set { this.failedFieldSpecified = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public sbyte timeout
        {
            get { return this.timeoutField; }
            set { this.timeoutField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool timeoutSpecified
        {
            get { return this.timeoutFieldSpecified; }
            set { this.timeoutFieldSpecified = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public sbyte aborted
        {
            get { return this.abortedField; }
            set { this.abortedField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool abortedSpecified
        {
            get { return this.abortedFieldSpecified; }
            set { this.abortedFieldSpecified = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public sbyte inconclusive
        {
            get { return this.inconclusiveField; }
            set { this.inconclusiveField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool inconclusiveSpecified
        {
            get { return this.inconclusiveFieldSpecified; }
            set { this.inconclusiveFieldSpecified = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public sbyte passedButRunAborted
        {
            get { return this.passedButRunAbortedField; }
            set { this.passedButRunAbortedField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool passedButRunAbortedSpecified
        {
            get { return this.passedButRunAbortedFieldSpecified; }
            set { this.passedButRunAbortedFieldSpecified = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public sbyte notRunnable
        {
            get { return this.notRunnableField; }
            set { this.notRunnableField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool notRunnableSpecified
        {
            get { return this.notRunnableFieldSpecified; }
            set { this.notRunnableFieldSpecified = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public sbyte notExecuted
        {
            get { return this.notExecutedField; }
            set { this.notExecutedField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool notExecutedSpecified
        {
            get { return this.notExecutedFieldSpecified; }
            set { this.notExecutedFieldSpecified = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public sbyte disconnected
        {
            get { return this.disconnectedField; }
            set { this.disconnectedField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool disconnectedSpecified
        {
            get { return this.disconnectedFieldSpecified; }
            set { this.disconnectedFieldSpecified = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public sbyte warning
        {
            get { return this.warningField; }
            set { this.warningField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool warningSpecified
        {
            get { return this.warningFieldSpecified; }
            set { this.warningFieldSpecified = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public sbyte passed
        {
            get { return this.passedField; }
            set { this.passedField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool passedSpecified
        {
            get { return this.passedFieldSpecified; }
            set { this.passedFieldSpecified = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public sbyte completed
        {
            get { return this.completedField; }
            set { this.completedField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool completedSpecified
        {
            get { return this.completedFieldSpecified; }
            set { this.completedFieldSpecified = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public sbyte inProgress
        {
            get { return this.inProgressField; }
            set { this.inProgressField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool inProgressSpecified
        {
            get { return this.inProgressFieldSpecified; }
            set { this.inProgressFieldSpecified = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public sbyte pending
        {
            get { return this.pendingField; }
            set { this.pendingField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool pendingSpecified
        {
            get { return this.pendingFieldSpecified; }
            set { this.pendingFieldSpecified = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value
        {
            get { return this.valueField; }
            set { this.valueField = value; }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true,
        Namespace = "http://microsoft.com/schemas/VisualStudio/TeamTest/2010")]
    public partial class TestRunResultsUnitTestResultInnerResults
    {

        private TestRunResultsUnitTestResultInnerResultsUnitTestResult unitTestResultField;

        /// <remarks/>
        public TestRunResultsUnitTestResultInnerResultsUnitTestResult UnitTestResult
        {
            get { return this.unitTestResultField; }
            set { this.unitTestResultField = value; }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true,
        Namespace = "http://microsoft.com/schemas/VisualStudio/TeamTest/2010")]
    public partial class TestRunResultsUnitTestResultInnerResultsUnitTestResult
    {

        private TestRunResultsUnitTestResultInnerResultsUnitTestResultOutput outputField;

        private string extensionResultField;

        private string executionIdField;

        private string parentExecutionIdField;

        private string testIdField;

        private string testNameField;

        private string computerNameField;

        private System.DateTime durationField;

        private bool durationFieldSpecified;

        private System.DateTime startTimeField;

        private bool startTimeFieldSpecified;

        private System.DateTime endTimeField;

        private bool endTimeFieldSpecified;

        private string testTypeField;

        private string outcomeField;

        private string testListIdField;

        private string relativeResultsDirectoryField;

        private sbyte dataRowInfoField;

        private bool dataRowInfoFieldSpecified;

        private string resultTypeField;

        /// <remarks/>
        public TestRunResultsUnitTestResultInnerResultsUnitTestResultOutput Output
        {
            get { return this.outputField; }
            set { this.outputField = value; }
        }

        /// <remarks/>
        public string ExtensionResult
        {
            get { return this.extensionResultField; }
            set { this.extensionResultField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string executionId
        {
            get { return this.executionIdField; }
            set { this.executionIdField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string parentExecutionId
        {
            get { return this.parentExecutionIdField; }
            set { this.parentExecutionIdField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string testId
        {
            get { return this.testIdField; }
            set { this.testIdField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string testName
        {
            get { return this.testNameField; }
            set { this.testNameField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string computerName
        {
            get { return this.computerNameField; }
            set { this.computerNameField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType = "time")]
        public System.DateTime duration
        {
            get { return this.durationField; }
            set { this.durationField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool durationSpecified
        {
            get { return this.durationFieldSpecified; }
            set { this.durationFieldSpecified = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public System.DateTime startTime
        {
            get { return this.startTimeField; }
            set { this.startTimeField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool startTimeSpecified
        {
            get { return this.startTimeFieldSpecified; }
            set { this.startTimeFieldSpecified = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public System.DateTime endTime
        {
            get { return this.endTimeField; }
            set { this.endTimeField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool endTimeSpecified
        {
            get { return this.endTimeFieldSpecified; }
            set { this.endTimeFieldSpecified = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string testType
        {
            get { return this.testTypeField; }
            set { this.testTypeField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string outcome
        {
            get { return this.outcomeField; }
            set { this.outcomeField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string testListId
        {
            get { return this.testListIdField; }
            set { this.testListIdField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string relativeResultsDirectory
        {
            get { return this.relativeResultsDirectoryField; }
            set { this.relativeResultsDirectoryField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public sbyte dataRowInfo
        {
            get { return this.dataRowInfoField; }
            set { this.dataRowInfoField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool dataRowInfoSpecified
        {
            get { return this.dataRowInfoFieldSpecified; }
            set { this.dataRowInfoFieldSpecified = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string resultType
        {
            get { return this.resultTypeField; }
            set { this.resultTypeField = value; }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true,
        Namespace = "http://microsoft.com/schemas/VisualStudio/TeamTest/2010")]
    public partial class TestRunResultsUnitTestResultInnerResultsUnitTestResultOutput
    {

        private TestRunResultsUnitTestResultInnerResultsUnitTestResultOutputErrorInfo errorInfoField;

        /// <remarks/>
        public TestRunResultsUnitTestResultInnerResultsUnitTestResultOutputErrorInfo ErrorInfo
        {
            get { return this.errorInfoField; }
            set { this.errorInfoField = value; }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true,
        Namespace = "http://microsoft.com/schemas/VisualStudio/TeamTest/2010")]
    public partial class TestRunResultsUnitTestResultInnerResultsUnitTestResultOutputErrorInfo
    {

        private string messageField;

        private string stackTraceField;

        /// <remarks/>
        public string Message
        {
            get { return this.messageField; }
            set { this.messageField = value; }
        }

        /// <remarks/>
        public string StackTrace
        {
            get { return this.stackTraceField; }
            set { this.stackTraceField = value; }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true,
        Namespace = "http://microsoft.com/schemas/VisualStudio/TeamTest/2010")]
    public partial class TestRunResultsTestResultAggregation
    {

        private TestRunResultsTestResultAggregationCounters countersField;

        private TestRunResultsTestResultAggregationUnitTestResult[] innerResultsField;

        private string executionIdField;

        private string testIdField;

        private string testNameField;

        private string computerNameField;

        private System.DateTime durationField;

        private bool durationFieldSpecified;

        private System.DateTime startTimeField;

        private bool startTimeFieldSpecified;

        private System.DateTime endTimeField;

        private bool endTimeFieldSpecified;

        private string testTypeField;

        private string outcomeField;

        private string testListIdField;

        private string relativeResultsDirectoryField;

        /// <remarks/>
        public TestRunResultsTestResultAggregationCounters Counters
        {
            get { return this.countersField; }
            set { this.countersField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("UnitTestResult", IsNullable = false)]
        public TestRunResultsTestResultAggregationUnitTestResult[] InnerResults
        {
            get { return this.innerResultsField; }
            set { this.innerResultsField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string executionId
        {
            get { return this.executionIdField; }
            set { this.executionIdField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string testId
        {
            get { return this.testIdField; }
            set { this.testIdField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string testName
        {
            get { return this.testNameField; }
            set { this.testNameField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string computerName
        {
            get { return this.computerNameField; }
            set { this.computerNameField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType = "time")]
        public System.DateTime duration
        {
            get { return this.durationField; }
            set { this.durationField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool durationSpecified
        {
            get { return this.durationFieldSpecified; }
            set { this.durationFieldSpecified = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public System.DateTime startTime
        {
            get { return this.startTimeField; }
            set { this.startTimeField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool startTimeSpecified
        {
            get { return this.startTimeFieldSpecified; }
            set { this.startTimeFieldSpecified = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public System.DateTime endTime
        {
            get { return this.endTimeField; }
            set { this.endTimeField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool endTimeSpecified
        {
            get { return this.endTimeFieldSpecified; }
            set { this.endTimeFieldSpecified = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string testType
        {
            get { return this.testTypeField; }
            set { this.testTypeField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string outcome
        {
            get { return this.outcomeField; }
            set { this.outcomeField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string testListId
        {
            get { return this.testListIdField; }
            set { this.testListIdField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string relativeResultsDirectory
        {
            get { return this.relativeResultsDirectoryField; }
            set { this.relativeResultsDirectoryField = value; }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true,
        Namespace = "http://microsoft.com/schemas/VisualStudio/TeamTest/2010")]
    public partial class TestRunResultsTestResultAggregationCounters
    {

        private sbyte errorField;

        private bool errorFieldSpecified;

        private sbyte failedField;

        private bool failedFieldSpecified;

        private sbyte timeoutField;

        private bool timeoutFieldSpecified;

        private sbyte abortedField;

        private bool abortedFieldSpecified;

        private sbyte inconclusiveField;

        private bool inconclusiveFieldSpecified;

        private sbyte passedButRunAbortedField;

        private bool passedButRunAbortedFieldSpecified;

        private sbyte notRunnableField;

        private bool notRunnableFieldSpecified;

        private sbyte notExecutedField;

        private bool notExecutedFieldSpecified;

        private sbyte disconnectedField;

        private bool disconnectedFieldSpecified;

        private sbyte warningField;

        private bool warningFieldSpecified;

        private sbyte passedField;

        private bool passedFieldSpecified;

        private sbyte completedField;

        private bool completedFieldSpecified;

        private sbyte inProgressField;

        private bool inProgressFieldSpecified;

        private sbyte pendingField;

        private bool pendingFieldSpecified;

        private string valueField;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public sbyte error
        {
            get { return this.errorField; }
            set { this.errorField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool errorSpecified
        {
            get { return this.errorFieldSpecified; }
            set { this.errorFieldSpecified = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public sbyte failed
        {
            get { return this.failedField; }
            set { this.failedField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool failedSpecified
        {
            get { return this.failedFieldSpecified; }
            set { this.failedFieldSpecified = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public sbyte timeout
        {
            get { return this.timeoutField; }
            set { this.timeoutField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool timeoutSpecified
        {
            get { return this.timeoutFieldSpecified; }
            set { this.timeoutFieldSpecified = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public sbyte aborted
        {
            get { return this.abortedField; }
            set { this.abortedField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool abortedSpecified
        {
            get { return this.abortedFieldSpecified; }
            set { this.abortedFieldSpecified = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public sbyte inconclusive
        {
            get { return this.inconclusiveField; }
            set { this.inconclusiveField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool inconclusiveSpecified
        {
            get { return this.inconclusiveFieldSpecified; }
            set { this.inconclusiveFieldSpecified = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public sbyte passedButRunAborted
        {
            get { return this.passedButRunAbortedField; }
            set { this.passedButRunAbortedField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool passedButRunAbortedSpecified
        {
            get { return this.passedButRunAbortedFieldSpecified; }
            set { this.passedButRunAbortedFieldSpecified = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public sbyte notRunnable
        {
            get { return this.notRunnableField; }
            set { this.notRunnableField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool notRunnableSpecified
        {
            get { return this.notRunnableFieldSpecified; }
            set { this.notRunnableFieldSpecified = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public sbyte notExecuted
        {
            get { return this.notExecutedField; }
            set { this.notExecutedField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool notExecutedSpecified
        {
            get { return this.notExecutedFieldSpecified; }
            set { this.notExecutedFieldSpecified = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public sbyte disconnected
        {
            get { return this.disconnectedField; }
            set { this.disconnectedField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool disconnectedSpecified
        {
            get { return this.disconnectedFieldSpecified; }
            set { this.disconnectedFieldSpecified = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public sbyte warning
        {
            get { return this.warningField; }
            set { this.warningField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool warningSpecified
        {
            get { return this.warningFieldSpecified; }
            set { this.warningFieldSpecified = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public sbyte passed
        {
            get { return this.passedField; }
            set { this.passedField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool passedSpecified
        {
            get { return this.passedFieldSpecified; }
            set { this.passedFieldSpecified = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public sbyte completed
        {
            get { return this.completedField; }
            set { this.completedField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool completedSpecified
        {
            get { return this.completedFieldSpecified; }
            set { this.completedFieldSpecified = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public sbyte inProgress
        {
            get { return this.inProgressField; }
            set { this.inProgressField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool inProgressSpecified
        {
            get { return this.inProgressFieldSpecified; }
            set { this.inProgressFieldSpecified = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public sbyte pending
        {
            get { return this.pendingField; }
            set { this.pendingField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool pendingSpecified
        {
            get { return this.pendingFieldSpecified; }
            set { this.pendingFieldSpecified = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value
        {
            get { return this.valueField; }
            set { this.valueField = value; }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true,
        Namespace = "http://microsoft.com/schemas/VisualStudio/TeamTest/2010")]
    public partial class TestRunResultsTestResultAggregationUnitTestResult
    {

        private TestRunResultsTestResultAggregationUnitTestResultOutput outputField;

        private TestRunResultsTestResultAggregationUnitTestResultResultFiles resultFilesField;

        private string extensionResultField;

        private string executionIdField;

        private string parentExecutionIdField;

        private string testIdField;

        private string testNameField;

        private string computerNameField;

        private System.DateTime durationField;

        private bool durationFieldSpecified;

        private System.DateTime startTimeField;

        private bool startTimeFieldSpecified;

        private System.DateTime endTimeField;

        private bool endTimeFieldSpecified;

        private string testTypeField;

        private string outcomeField;

        private string testListIdField;

        private string relativeResultsDirectoryField;

        /// <remarks/>
        public TestRunResultsTestResultAggregationUnitTestResultOutput Output
        {
            get { return this.outputField; }
            set { this.outputField = value; }
        }

        /// <remarks/>
        public TestRunResultsTestResultAggregationUnitTestResultResultFiles ResultFiles
        {
            get { return this.resultFilesField; }
            set { this.resultFilesField = value; }
        }

        /// <remarks/>
        public string ExtensionResult
        {
            get { return this.extensionResultField; }
            set { this.extensionResultField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string executionId
        {
            get { return this.executionIdField; }
            set { this.executionIdField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string parentExecutionId
        {
            get { return this.parentExecutionIdField; }
            set { this.parentExecutionIdField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string testId
        {
            get { return this.testIdField; }
            set { this.testIdField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string testName
        {
            get { return this.testNameField; }
            set { this.testNameField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string computerName
        {
            get { return this.computerNameField; }
            set { this.computerNameField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType = "time")]
        public System.DateTime duration
        {
            get { return this.durationField; }
            set { this.durationField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool durationSpecified
        {
            get { return this.durationFieldSpecified; }
            set { this.durationFieldSpecified = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public System.DateTime startTime
        {
            get { return this.startTimeField; }
            set { this.startTimeField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool startTimeSpecified
        {
            get { return this.startTimeFieldSpecified; }
            set { this.startTimeFieldSpecified = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public System.DateTime endTime
        {
            get { return this.endTimeField; }
            set { this.endTimeField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool endTimeSpecified
        {
            get { return this.endTimeFieldSpecified; }
            set { this.endTimeFieldSpecified = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string testType
        {
            get { return this.testTypeField; }
            set { this.testTypeField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string outcome
        {
            get { return this.outcomeField; }
            set { this.outcomeField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string testListId
        {
            get { return this.testListIdField; }
            set { this.testListIdField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string relativeResultsDirectory
        {
            get { return this.relativeResultsDirectoryField; }
            set { this.relativeResultsDirectoryField = value; }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true,
        Namespace = "http://microsoft.com/schemas/VisualStudio/TeamTest/2010")]
    public partial class TestRunResultsTestResultAggregationUnitTestResultOutput
    {

        private TestRunResultsTestResultAggregationUnitTestResultOutputErrorInfo errorInfoField;

        private string[] textMessagesField;

        /// <remarks/>
        public TestRunResultsTestResultAggregationUnitTestResultOutputErrorInfo ErrorInfo
        {
            get { return this.errorInfoField; }
            set { this.errorInfoField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("Message", IsNullable = false)]
        public string[] TextMessages
        {
            get { return this.textMessagesField; }
            set { this.textMessagesField = value; }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true,
        Namespace = "http://microsoft.com/schemas/VisualStudio/TeamTest/2010")]
    public partial class TestRunResultsTestResultAggregationUnitTestResultOutputErrorInfo
    {

        private string messageField;

        private string stackTraceField;

        /// <remarks/>
        public string Message
        {
            get { return this.messageField; }
            set { this.messageField = value; }
        }

        /// <remarks/>
        public string StackTrace
        {
            get { return this.stackTraceField; }
            set { this.stackTraceField = value; }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true,
        Namespace = "http://microsoft.com/schemas/VisualStudio/TeamTest/2010")]
    public partial class TestRunResultsTestResultAggregationUnitTestResultResultFiles
    {

        private TestRunResultsTestResultAggregationUnitTestResultResultFilesResultFile resultFileField;

        /// <remarks/>
        public TestRunResultsTestResultAggregationUnitTestResultResultFilesResultFile ResultFile
        {
            get { return this.resultFileField; }
            set { this.resultFileField = value; }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true,
        Namespace = "http://microsoft.com/schemas/VisualStudio/TeamTest/2010")]
    public partial class TestRunResultsTestResultAggregationUnitTestResultResultFilesResultFile
    {

        private string pathField;

        private string valueField;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string path
        {
            get { return this.pathField; }
            set { this.pathField = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value
        {
            get { return this.valueField; }
            set { this.valueField = value; }
        }
    }
}
